### PR TITLE
Add support for enclosed ' ' parameters in MongoD

### PR DESCRIPTION
**Pull request by renanwilliam**
Creating some tests with MongoDB I was looked a problem with id keys enclosed with " ' ".
In collection document the meta link for individual entries are not working in these cases.

### CODE REVIEW

**Comment by htammen** [comment]
I just wanting to merge your pull request. To ensure that there are no side effects I would like to test it on my side. Could you please send me a model definition file (.json) from your common/models folder that produces the error you fixed?
I'm especially interested in the definition of the id field. I don't need each property definition.

Thx Helmut

**Comment by htammen** [comment]
Just debugged it. I have a generated id in one of my models that does not produce an id that ist enclosed by '" ' ".  In that case your change would lead to an undefined id.

**Comment by renanwilliam** [comment]
Are you checked my last 2 commits? I have checked the 'undefined id' and fixed it in commits 2dc2af4
and df79758.

Check the model 'CoffeShop' in this repo: https://github.com/renanwilliam/n-odata-server-example

**Comment by htammen** [comment]
I merged your pull request and made a little fix to it. You forgot an else if property is generated and rawId is not starting with a quote.

Thx for contributing to the project.

**Pull request merged**
